---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
        name: Check yaml files
      - id: trailing-whitespace
        name: Check trailing whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
        name: Check yaml files (yamllint)
  - repo: local
    hooks:
      - id: docker-markdownlint
        name: Run markdownlint with docker
        entry: markdownlint/markdownlint -r "~MD013"
        language: docker_image
        types: [markdown]
      - id: docker-shell-shfmt
        name: Run shfmt with docker
        entry: mvdan/shfmt:latest -d -i 2 -ci
        language: docker_image
        types: [shell]
      - id: docker-shell-lint
        name: Run shellcheck with docker
        language: docker_image
        entry: koalaman/shellcheck:stable
        types: [shell]
      - id: docker-hadolint
        name: Run hadolint with docker
        language: docker_image
        entry: hadolint/hadolint:latest hadolint
        files: Dockerfile
      - id: docker-prettier
        name: Run prettier with docker
        entry: tmknom/prettier:latest -l
        language: docker_image
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |js|jsx\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"
